# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joe Tuson
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Coding n stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joetuson.com" # the base hostname & protocol for your site

# Build settings
show_excerpts: true # set to true to show excerpts on the homepage
markdown: kramdown
sass:
  sass_dir: _sass



# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md

# theme
remote_theme: samarsault/plainwhite-jekyll
#theme: plainwhite

plainwhite:
  name: Joe Tuson
  tagline: Coaching for Managers
  date_format: "%b %-d, %Y"
  analytics_id: "UA-74448671-1"

  social_links:
    linkedIn: in/joetuson # format: locale/username

  navigation:
    - title: About
      url: "/about"


